words:
  - bunc
  - CDPATH
  - darwin
  - fobjc
  - getline
  - gsub
  - javac
  - javai
  - jitless
  - kbytes
  - linux
  - mkfifo
  - nodei
  - objc
  - quickjs
  - rustc
  - scriptc
  - scriptcc
  - swiftc
  - TMPDIR
  - Xint